dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

install:
    - sudo apt-get update
    - sudo apt-get install valgrind
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    - sudo apt-get install cppcheck

script:
    - cmake .
    - make
    # valgrind
    - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./tests.out
    # cppcheck
    - cppcheck --quiet --error-exitcode=1 .
