#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - tests
# blacklist
  except:
    - master
    - project/travis

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\myproject
shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

matrix:
  fast_finish: false

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64
  - Any CPU

# several configurations to build matrix:
configuration:
  - Debug
  - Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmake .
  - make

test_script:
  - ctest .